### ISSUE TITLE
Update parent image to debian:bullseye-slim

### ISSUE THREAD

**Issue by anthonyfok** [OpenDRR/python-env#3]
With the release of Debian 11 (bullseye) in August 2021, it would be nice to update our current parent image `debian:sid-20200720-slim` to `debian:bullseye-slim`.

One of the major changes in Debian 11 is the transition from Python 3.7 (or Python 3.8.5 in sid in July 2020) to Python 3.9, which implies the need to upgrade various Python libraries and to revise our existing Python scripts where necessary.

Would be nice to have to have GitHub Actions CI/CD set up first, though not strictly necessary in that order.

**Comment by jvanulde** [comment]
@anthonyfok will this be resolved by https://github.com/OpenDRR/python-env/pull/7?

**Comment by anthonyfok** [comment]
@jvanulde Sorry for my (very) tardy reply!

> @anthonyfok will this be resolved by https://github.com/OpenDRR/python-env/pull/7? (now #69)

Normally yes, but there are some needed changes for moving from a Debian unstable (sid) snapshot to a stable release (e.g. APT repository URLs) and other tweaks that I wanted to make, such that I'm using Pull Request #72 instead to resolve this issue.
