### ISSUE TITLE
Update ElasticSearch version 

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/python-env#5]
Current version may present a security vulnerability

**Comment by anthonyfok** [comment]
Our python-env image contains the Python elasticsearch module only and no Java stuff at all (no Log4j, etc.), so thankfully it was not affected by the Log4j vulnerability.  However, it is indeed a good idea to match the version of Python module to that of the Elasticsearch v7.16.1 (Java) Docker image being used at OpenDRR/opendrr-api.  That was completed with the merge of

* #4

and the [release of v1.1.0 of the python-env image](https://github.com/OpenDRR/python-env/releases/tag/v1.1.0).
